// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contacts.proto

package com.premkumar.springmvcprotobuf.proto;

public final class ContactsProtos {
  private ContactsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ContactOrBuilder extends
      // @@protoc_insertion_point(interface_extends:src.main.java.Contact)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string mobile = 4;</code>
     */
    java.lang.String getMobile();
    /**
     * <code>string mobile = 4;</code>
     */
    com.google.protobuf.ByteString
        getMobileBytes();

    /**
     * <code>.src.main.java.Contact.ContactType contactType = 5;</code>
     */
    int getContactTypeValue();
    /**
     * <code>.src.main.java.Contact.ContactType contactType = 5;</code>
     */
    com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.ContactType getContactType();
  }
  /**
   * Protobuf type {@code src.main.java.Contact}
   */
  public  static final class Contact extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:src.main.java.Contact)
      ContactOrBuilder {
    // Use Contact.newBuilder() to construct.
    private Contact(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Contact() {
      id_ = 0;
      name_ = "";
      email_ = "";
      mobile_ = "";
      contactType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Contact(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              mobile_ = s;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              contactType_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.premkumar.springmvcprotobuf.proto.ContactsProtos.internal_static_src_main_java_Contact_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.premkumar.springmvcprotobuf.proto.ContactsProtos.internal_static_src_main_java_Contact_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.class, com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.Builder.class);
    }

    /**
     * Protobuf enum {@code src.main.java.Contact.ContactType}
     */
    public enum ContactType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>FRIEND = 0;</code>
       */
      FRIEND(0),
      /**
       * <code>FAMILY = 1;</code>
       */
      FAMILY(1),
      /**
       * <code>WORK = 2;</code>
       */
      WORK(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>FRIEND = 0;</code>
       */
      public static final int FRIEND_VALUE = 0;
      /**
       * <code>FAMILY = 1;</code>
       */
      public static final int FAMILY_VALUE = 1;
      /**
       * <code>WORK = 2;</code>
       */
      public static final int WORK_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ContactType valueOf(int value) {
        return forNumber(value);
      }

      public static ContactType forNumber(int value) {
        switch (value) {
          case 0: return FRIEND;
          case 1: return FAMILY;
          case 2: return WORK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ContactType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ContactType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ContactType>() {
              public ContactType findValueByNumber(int number) {
                return ContactType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.getDescriptor().getEnumTypes().get(0);
      }

      private static final ContactType[] VALUES = values();

      public static ContactType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ContactType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:src.main.java.Contact.ContactType)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MOBILE_FIELD_NUMBER = 4;
    private volatile java.lang.Object mobile_;
    /**
     * <code>string mobile = 4;</code>
     */
    public java.lang.String getMobile() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mobile_ = s;
        return s;
      }
    }
    /**
     * <code>string mobile = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMobileBytes() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTACTTYPE_FIELD_NUMBER = 5;
    private int contactType_;
    /**
     * <code>.src.main.java.Contact.ContactType contactType = 5;</code>
     */
    public int getContactTypeValue() {
      return contactType_;
    }
    /**
     * <code>.src.main.java.Contact.ContactType contactType = 5;</code>
     */
    public com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.ContactType getContactType() {
      com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.ContactType result = com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.ContactType.valueOf(contactType_);
      return result == null ? com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.ContactType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      if (!getMobileBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, mobile_);
      }
      if (contactType_ != com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.ContactType.FRIEND.getNumber()) {
        output.writeEnum(5, contactType_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      if (!getMobileBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, mobile_);
      }
      if (contactType_ != com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.ContactType.FRIEND.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, contactType_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact)) {
        return super.equals(obj);
      }
      com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact other = (com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && getEmail()
          .equals(other.getEmail());
      result = result && getMobile()
          .equals(other.getMobile());
      result = result && contactType_ == other.contactType_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + MOBILE_FIELD_NUMBER;
      hash = (53 * hash) + getMobile().hashCode();
      hash = (37 * hash) + CONTACTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + contactType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code src.main.java.Contact}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:src.main.java.Contact)
        com.premkumar.springmvcprotobuf.proto.ContactsProtos.ContactOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.premkumar.springmvcprotobuf.proto.ContactsProtos.internal_static_src_main_java_Contact_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.premkumar.springmvcprotobuf.proto.ContactsProtos.internal_static_src_main_java_Contact_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.class, com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.Builder.class);
      }

      // Construct using com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        email_ = "";

        mobile_ = "";

        contactType_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.premkumar.springmvcprotobuf.proto.ContactsProtos.internal_static_src_main_java_Contact_descriptor;
      }

      public com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact getDefaultInstanceForType() {
        return com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.getDefaultInstance();
      }

      public com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact build() {
        com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact buildPartial() {
        com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact result = new com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact(this);
        result.id_ = id_;
        result.name_ = name_;
        result.email_ = email_;
        result.mobile_ = mobile_;
        result.contactType_ = contactType_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact) {
          return mergeFrom((com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact other) {
        if (other == com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (!other.getMobile().isEmpty()) {
          mobile_ = other.mobile_;
          onChanged();
        }
        if (other.contactType_ != 0) {
          setContactTypeValue(other.getContactTypeValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object mobile_ = "";
      /**
       * <code>string mobile = 4;</code>
       */
      public java.lang.String getMobile() {
        java.lang.Object ref = mobile_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mobile_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mobile = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMobileBytes() {
        java.lang.Object ref = mobile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mobile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mobile = 4;</code>
       */
      public Builder setMobile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mobile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mobile = 4;</code>
       */
      public Builder clearMobile() {
        
        mobile_ = getDefaultInstance().getMobile();
        onChanged();
        return this;
      }
      /**
       * <code>string mobile = 4;</code>
       */
      public Builder setMobileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mobile_ = value;
        onChanged();
        return this;
      }

      private int contactType_ = 0;
      /**
       * <code>.src.main.java.Contact.ContactType contactType = 5;</code>
       */
      public int getContactTypeValue() {
        return contactType_;
      }
      /**
       * <code>.src.main.java.Contact.ContactType contactType = 5;</code>
       */
      public Builder setContactTypeValue(int value) {
        contactType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.src.main.java.Contact.ContactType contactType = 5;</code>
       */
      public com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.ContactType getContactType() {
        com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.ContactType result = com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.ContactType.valueOf(contactType_);
        return result == null ? com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.ContactType.UNRECOGNIZED : result;
      }
      /**
       * <code>.src.main.java.Contact.ContactType contactType = 5;</code>
       */
      public Builder setContactType(com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.ContactType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        contactType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.src.main.java.Contact.ContactType contactType = 5;</code>
       */
      public Builder clearContactType() {
        
        contactType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:src.main.java.Contact)
    }

    // @@protoc_insertion_point(class_scope:src.main.java.Contact)
    private static final com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact();
    }

    public static com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Contact>
        PARSER = new com.google.protobuf.AbstractParser<Contact>() {
      public Contact parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Contact(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Contact> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Contact> getParserForType() {
      return PARSER;
    }

    public com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddressBookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:src.main.java.AddressBook)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .src.main.java.Contact contacts = 1;</code>
     */
    java.util.List<com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact> 
        getContactsList();
    /**
     * <code>repeated .src.main.java.Contact contacts = 1;</code>
     */
    com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact getContacts(int index);
    /**
     * <code>repeated .src.main.java.Contact contacts = 1;</code>
     */
    int getContactsCount();
    /**
     * <code>repeated .src.main.java.Contact contacts = 1;</code>
     */
    java.util.List<? extends com.premkumar.springmvcprotobuf.proto.ContactsProtos.ContactOrBuilder> 
        getContactsOrBuilderList();
    /**
     * <code>repeated .src.main.java.Contact contacts = 1;</code>
     */
    com.premkumar.springmvcprotobuf.proto.ContactsProtos.ContactOrBuilder getContactsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code src.main.java.AddressBook}
   */
  public  static final class AddressBook extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:src.main.java.AddressBook)
      AddressBookOrBuilder {
    // Use AddressBook.newBuilder() to construct.
    private AddressBook(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddressBook() {
      contacts_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AddressBook(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                contacts_ = new java.util.ArrayList<com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact>();
                mutable_bitField0_ |= 0x00000001;
              }
              contacts_.add(
                  input.readMessage(com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          contacts_ = java.util.Collections.unmodifiableList(contacts_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.premkumar.springmvcprotobuf.proto.ContactsProtos.internal_static_src_main_java_AddressBook_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.premkumar.springmvcprotobuf.proto.ContactsProtos.internal_static_src_main_java_AddressBook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook.class, com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook.Builder.class);
    }

    public static final int CONTACTS_FIELD_NUMBER = 1;
    private java.util.List<com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact> contacts_;
    /**
     * <code>repeated .src.main.java.Contact contacts = 1;</code>
     */
    public java.util.List<com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact> getContactsList() {
      return contacts_;
    }
    /**
     * <code>repeated .src.main.java.Contact contacts = 1;</code>
     */
    public java.util.List<? extends com.premkumar.springmvcprotobuf.proto.ContactsProtos.ContactOrBuilder> 
        getContactsOrBuilderList() {
      return contacts_;
    }
    /**
     * <code>repeated .src.main.java.Contact contacts = 1;</code>
     */
    public int getContactsCount() {
      return contacts_.size();
    }
    /**
     * <code>repeated .src.main.java.Contact contacts = 1;</code>
     */
    public com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact getContacts(int index) {
      return contacts_.get(index);
    }
    /**
     * <code>repeated .src.main.java.Contact contacts = 1;</code>
     */
    public com.premkumar.springmvcprotobuf.proto.ContactsProtos.ContactOrBuilder getContactsOrBuilder(
        int index) {
      return contacts_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < contacts_.size(); i++) {
        output.writeMessage(1, contacts_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < contacts_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, contacts_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook)) {
        return super.equals(obj);
      }
      com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook other = (com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook) obj;

      boolean result = true;
      result = result && getContactsList()
          .equals(other.getContactsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getContactsCount() > 0) {
        hash = (37 * hash) + CONTACTS_FIELD_NUMBER;
        hash = (53 * hash) + getContactsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code src.main.java.AddressBook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:src.main.java.AddressBook)
        com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.premkumar.springmvcprotobuf.proto.ContactsProtos.internal_static_src_main_java_AddressBook_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.premkumar.springmvcprotobuf.proto.ContactsProtos.internal_static_src_main_java_AddressBook_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook.class, com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook.Builder.class);
      }

      // Construct using com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getContactsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (contactsBuilder_ == null) {
          contacts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          contactsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.premkumar.springmvcprotobuf.proto.ContactsProtos.internal_static_src_main_java_AddressBook_descriptor;
      }

      public com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook getDefaultInstanceForType() {
        return com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook.getDefaultInstance();
      }

      public com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook build() {
        com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook buildPartial() {
        com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook result = new com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook(this);
        int from_bitField0_ = bitField0_;
        if (contactsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            contacts_ = java.util.Collections.unmodifiableList(contacts_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.contacts_ = contacts_;
        } else {
          result.contacts_ = contactsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook) {
          return mergeFrom((com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook other) {
        if (other == com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook.getDefaultInstance()) return this;
        if (contactsBuilder_ == null) {
          if (!other.contacts_.isEmpty()) {
            if (contacts_.isEmpty()) {
              contacts_ = other.contacts_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureContactsIsMutable();
              contacts_.addAll(other.contacts_);
            }
            onChanged();
          }
        } else {
          if (!other.contacts_.isEmpty()) {
            if (contactsBuilder_.isEmpty()) {
              contactsBuilder_.dispose();
              contactsBuilder_ = null;
              contacts_ = other.contacts_;
              bitField0_ = (bitField0_ & ~0x00000001);
              contactsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getContactsFieldBuilder() : null;
            } else {
              contactsBuilder_.addAllMessages(other.contacts_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact> contacts_ =
        java.util.Collections.emptyList();
      private void ensureContactsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          contacts_ = new java.util.ArrayList<com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact>(contacts_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact, com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.Builder, com.premkumar.springmvcprotobuf.proto.ContactsProtos.ContactOrBuilder> contactsBuilder_;

      /**
       * <code>repeated .src.main.java.Contact contacts = 1;</code>
       */
      public java.util.List<com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact> getContactsList() {
        if (contactsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(contacts_);
        } else {
          return contactsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .src.main.java.Contact contacts = 1;</code>
       */
      public int getContactsCount() {
        if (contactsBuilder_ == null) {
          return contacts_.size();
        } else {
          return contactsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .src.main.java.Contact contacts = 1;</code>
       */
      public com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact getContacts(int index) {
        if (contactsBuilder_ == null) {
          return contacts_.get(index);
        } else {
          return contactsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .src.main.java.Contact contacts = 1;</code>
       */
      public Builder setContacts(
          int index, com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact value) {
        if (contactsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactsIsMutable();
          contacts_.set(index, value);
          onChanged();
        } else {
          contactsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .src.main.java.Contact contacts = 1;</code>
       */
      public Builder setContacts(
          int index, com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.Builder builderForValue) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          contacts_.set(index, builderForValue.build());
          onChanged();
        } else {
          contactsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .src.main.java.Contact contacts = 1;</code>
       */
      public Builder addContacts(com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact value) {
        if (contactsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactsIsMutable();
          contacts_.add(value);
          onChanged();
        } else {
          contactsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .src.main.java.Contact contacts = 1;</code>
       */
      public Builder addContacts(
          int index, com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact value) {
        if (contactsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactsIsMutable();
          contacts_.add(index, value);
          onChanged();
        } else {
          contactsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .src.main.java.Contact contacts = 1;</code>
       */
      public Builder addContacts(
          com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.Builder builderForValue) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          contacts_.add(builderForValue.build());
          onChanged();
        } else {
          contactsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .src.main.java.Contact contacts = 1;</code>
       */
      public Builder addContacts(
          int index, com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.Builder builderForValue) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          contacts_.add(index, builderForValue.build());
          onChanged();
        } else {
          contactsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .src.main.java.Contact contacts = 1;</code>
       */
      public Builder addAllContacts(
          java.lang.Iterable<? extends com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact> values) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, contacts_);
          onChanged();
        } else {
          contactsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .src.main.java.Contact contacts = 1;</code>
       */
      public Builder clearContacts() {
        if (contactsBuilder_ == null) {
          contacts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          contactsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .src.main.java.Contact contacts = 1;</code>
       */
      public Builder removeContacts(int index) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          contacts_.remove(index);
          onChanged();
        } else {
          contactsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .src.main.java.Contact contacts = 1;</code>
       */
      public com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.Builder getContactsBuilder(
          int index) {
        return getContactsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .src.main.java.Contact contacts = 1;</code>
       */
      public com.premkumar.springmvcprotobuf.proto.ContactsProtos.ContactOrBuilder getContactsOrBuilder(
          int index) {
        if (contactsBuilder_ == null) {
          return contacts_.get(index);  } else {
          return contactsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .src.main.java.Contact contacts = 1;</code>
       */
      public java.util.List<? extends com.premkumar.springmvcprotobuf.proto.ContactsProtos.ContactOrBuilder> 
           getContactsOrBuilderList() {
        if (contactsBuilder_ != null) {
          return contactsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(contacts_);
        }
      }
      /**
       * <code>repeated .src.main.java.Contact contacts = 1;</code>
       */
      public com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.Builder addContactsBuilder() {
        return getContactsFieldBuilder().addBuilder(
            com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.getDefaultInstance());
      }
      /**
       * <code>repeated .src.main.java.Contact contacts = 1;</code>
       */
      public com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.Builder addContactsBuilder(
          int index) {
        return getContactsFieldBuilder().addBuilder(
            index, com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.getDefaultInstance());
      }
      /**
       * <code>repeated .src.main.java.Contact contacts = 1;</code>
       */
      public java.util.List<com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.Builder> 
           getContactsBuilderList() {
        return getContactsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact, com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.Builder, com.premkumar.springmvcprotobuf.proto.ContactsProtos.ContactOrBuilder> 
          getContactsFieldBuilder() {
        if (contactsBuilder_ == null) {
          contactsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact, com.premkumar.springmvcprotobuf.proto.ContactsProtos.Contact.Builder, com.premkumar.springmvcprotobuf.proto.ContactsProtos.ContactOrBuilder>(
                  contacts_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          contacts_ = null;
        }
        return contactsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:src.main.java.AddressBook)
    }

    // @@protoc_insertion_point(class_scope:src.main.java.AddressBook)
    private static final com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook();
    }

    public static com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddressBook>
        PARSER = new com.google.protobuf.AbstractParser<AddressBook>() {
      public AddressBook parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AddressBook(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AddressBook> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddressBook> getParserForType() {
      return PARSER;
    }

    public com.premkumar.springmvcprotobuf.proto.ContactsProtos.AddressBook getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_src_main_java_Contact_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_src_main_java_Contact_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_src_main_java_AddressBook_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_src_main_java_AddressBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016contacts.proto\022\rsrc.main.java\"\254\001\n\007Cont" +
      "act\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\r\n\005email\030\003" +
      " \001(\t\022\016\n\006mobile\030\004 \001(\t\0227\n\013contactType\030\005 \001(" +
      "\0162\".src.main.java.Contact.ContactType\"/\n" +
      "\013ContactType\022\n\n\006FRIEND\020\000\022\n\n\006FAMILY\020\001\022\010\n\004" +
      "WORK\020\002\"7\n\013AddressBook\022(\n\010contacts\030\001 \003(\0132" +
      "\026.src.main.java.ContactB7\n%com.premkumar" +
      ".springmvcprotobuf.protoB\016ContactsProtos" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_src_main_java_Contact_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_src_main_java_Contact_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_src_main_java_Contact_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", "Mobile", "ContactType", });
    internal_static_src_main_java_AddressBook_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_src_main_java_AddressBook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_src_main_java_AddressBook_descriptor,
        new java.lang.String[] { "Contacts", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
